[project]
name = "midgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "equinox==0.11.2",
    "gcsfs>=2025.2.0",
    "optax==0.1.7",
    "orbax==0.1.9",
    "rich==13.7.0",
    "tensorflow>=2.18.0",
    "tiktoken==0.5.1",
    "tqdm==4.66.1",
    "transformers==4.35.2",
    "wandb>=0.19.6",
]
